# A Quick Tour of TensorFlow

Tensorflow is a powerful library for numerical computation, particulary well suited and fine-tuned for large-scale Machine Learning (but you could use it for anything else that requires heavy computations).
* Same as Numpy, but with GPU support.
* supports distributed computing (across multiple devices and servers)
* just-in-time compiler
* implements autodiff
* most important tf.keras, data loading and preprocessing ops (tf.data, tf.io, etc), image processing ops (tf.image), signal processing ops (tf.signal), and more.

## Using Tensorflow as NumPy
A **tensor** is a multidimensional array (like NumPy ndarray), but it can also hold a scalar value (a simple value, such as 42).

### Tensors and Operations

In [2]:
# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

# Common imports
import numpy as np
import os

In [3]:
tf.constant([[1., 2., 3.], [4., 5., 6.]]) # matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
tf.constant(42) # scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [8]:
t.shape, t.dtype

(TensorShape([2, 3]), tf.float32)

#### Indexing

In [10]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [11]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

#### Ops

In [12]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [13]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

... to be continued.